version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: momnetwork
      POSTGRES_USER: mom
      POSTGRES_PASSWORD: mompass
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
