# Generated by Django 4.2.7 on 2025-09-02 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Nomination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nominator_name", models.CharField(max_length=100)),
                (
                    "nominator_email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("nominator_phone", models.CharField(blank=True, max_length=20)),
                ("relationship_to_nominee", models.CharField(max_length=100)),
                ("nominee_name", models.CharField(max_length=100)),
                (
                    "nominee_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("nominee_phone", models.CharField(blank=True, max_length=20)),
                ("nominee_address", models.CharField(max_length=200)),
                ("nominee_city", models.CharField(max_length=100)),
                ("nominee_state", models.CharField(max_length=50)),
                ("nominee_zip_code", models.CharField(max_length=10)),
                ("family_size", models.IntegerField()),
                ("children_ages", models.TextField(help_text="List ages of children")),
                ("why_nominating", models.TextField()),
                ("current_challenges", models.TextField()),
                ("how_help_would_impact", models.TextField()),
                ("additional_info", models.TextField(blank=True)),
                ("is_reviewed", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Nomination",
                "verbose_name_plural": "Nominations",
                "ordering": ["-created_at"],
            },
        ),
    ]
