# Generated by Django 4.2.7 on 2025-09-02 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.CharField(max_length=100)),
                (
                    "author_email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("author_city", models.CharField(blank=True, max_length=100)),
                ("author_state", models.CharField(blank=True, max_length=50)),
                ("title", models.CharField(max_length=200)),
                ("story_content", models.TextField()),
                (
                    "story_type",
                    models.CharField(
                        choices=[
                            ("received_help", "I Received Help"),
                            ("gave_help", "I Gave Help"),
                            ("community_impact", "Community Impact"),
                            ("inspiration", "Inspiration"),
                        ],
                        default="received_help",
                        max_length=20,
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Story",
                "verbose_name_plural": "Stories",
                "ordering": ["-created_at"],
            },
        ),
    ]
