# Generated by Django 4.2.7 on 2025-09-02 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeeklyWinner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("winner_name", models.CharField(max_length=100)),
                (
                    "winner_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=50)),
                ("family_size", models.IntegerField()),
                ("children_ages", models.TextField(blank=True)),
                (
                    "amount_received",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("week_ending", models.DateField()),
                ("story_summary", models.TextField()),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="winners/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Weekly Winner",
                "verbose_name_plural": "Weekly Winners",
                "ordering": ["-week_ending"],
            },
        ),
    ]
